name: portefolio
description: "Ce portfolio a √©t√© con√ßu pour illustrer mes comp√©tences en Flutter et offrir un aper√ßu clair et esth√©tique de mon parcours √† toute personne int√©ress√©e."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^3.0.3

  # Navigation
  go_router: ^17.0.0

  # UI & Animations
  cupertino_icons: ^1.0.8

  # PDF
  pdf: ^3.11.3
  printing: ^5.14.2

  # Video & Media
  youtube_player_iframe: ^5.2.2
  flutter_svg: ^2.2.1

  # Location & Maps
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  geolocator: ^14.0.2

  # Google outils
  google_fonts: ^8.0.2
  googleapis: ^16.0.0
  google_sign_in: ^7.2.0

  # HTTP & Network
  http: ^1.5.0

  # Data & Storage
  shared_preferences: ^2.5.3
  flutter_dotenv: ^6.0.0
  emailjs: ^4.0.0
  flutter_highlight: ^0.7.0
  timelines_plus: ^1.0.7
  flutter_animate: ^4.5.2
  hive: ^2.2.3
  flutter_colorpicker: ^1.1.0
  vector_math: ^2.2.0
  url_launcher: ^6.3.2
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  package_info_plus: ^9.0.0
  fl_chart: ^1.1.1
  lottie: ^3.3.2
  flutter_native_splash: ^2.4.7
  model_viewer_plus: ^1.9.3
  flutter_lucide: ^1.7.0
  flutter_map_tile_caching: ^10.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  riverpod_lint: ^3.0.3
  flutter_launcher_icons: ^0.14.4
  mocktail: ^1.0.4

dependency_overrides:
  # youtube_player_iframe_web: ^3.1.2
  # web: ^0.5.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/logos/
    - assets/images/animations/
    - assets/images/backgrounds/
    - assets/images/entreprises/
    - assets/images/realisations/
    - assets/images/services/
    - assets/images/Emap/
    - assets/images/WorkShop/
    - assets/images/models/
    - assets/data/
    - assets/fonts/Noto_Sans/
    - assets/fonts/Noto_Sans/static/

  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/Noto_Sans/NotoSans-VariableFont_wdth-wght.ttf
    - family: NotoSansItalic
      fonts:
        - asset: assets/fonts/Noto_Sans/NotoSans-Italic-VariableFont_wdth-wght.ttf


flutter_launcher_icons:
  # Chemin vers votre ic√¥ne haute r√©solution
  image_path: "assets/images/logos/godzyken_icon.png"
  # Plateformes cibles
  android: true
  ios: true
  # Configuration d√©taill√©e (map) requise pour Web, Linux, Windows
  web:
    generate: true
    image_path: "assets/images/logos/godzyken_icon.png"
  macos:
    generate: true
    image_path: "assets/images/logos/godzyken_icon.png"
  linux:
    generate: true
    image_path: "assets/images/logos/godzyken_icon.png"
  windows:
    generate: true
    image_path: "assets/images/logos/godzyken_icon.png"
    # icon_size: 48 # Optionnel : Sp√©cifie la taille de l'ic√¥ne Windows

  # OPTIONNEL : Pour garantir une ic√¥ne adaptative sur Android (recommand√©)
  # Si vous avez deux fichiers (avant-plan et arri√®re-plan)
  # adaptive_icon_foreground: "assets/images/logos/godzyken_icon_foreground.png"
  # adaptive_icon_background: "#FFFFFF" # ou un chemin vers l'image de fond

# üîç COMMANDES DE V√âRIFICATION (avec fvm) :
# flutter pub get
# flutter pub deps
# flutter analyze
# flutter doctor -v
# dart analyze lib/


# Generated by Spider
# For more info on configuration, visit https://birjuvachhani.github.io/spider/grouping/
spider:
  # Generates unit tests to verify that the assets exists in assets directory
  generate_tests: true
  # Use this to remove vcs noise created by the `generated` comments in dart code
  no_comments: true
  # Exports all the generated file as the one library
  export: true
  # This allows you to import all the generated references with 1 single import!
  use_part_of: true
  # Generates a variable that contains a list of all asset values.
  use_references_list: false
  # Generates files with given ignore rules for file.
  # ignored_rules:
  #   - public_member_api_docs
  # Generates dart font family references for fonts specified in pubspec.yaml
  # fonts: true
  # -------- OR --------
  # fonts:
  #   class_name: MyFonts
  #   file_name: my_fonts
  # Location where all the generated references will be stored
  package: resources
  groups:
    - path: assets/images
      class_name: Images
      types: [ .png, .jpg, .jpeg, .webp, .webm, .bmp ]